# copy this file and replace with your paths to the .ply files and output labels
# save as config_local.py

#In the Paris Lille Dataset should be something like Benchmark/training_10_classes/
#I trained on Lille1_1, Lille1_2, and paris and evaluated against lille2.ply you can do as you please
TRAINING_PLY_FILES = [
    r"/path/to/Lille1_1.ply",
    r"/path/to/Lille1_2.ply",
    r"/path/to/paris.ply"
]

VALIDATION_PLY_FILES = [
    r"/path/to/Lille2.ply"
]

#labeleweights generated by preprocessing script
VALIDATION_LABEL_WEIGHTS_PATH = r"/path/to/labelweights/labelweights.npy"
TRAINING_LABLE_WEIGHTS_PATH = r"/path/to/labelweights/labelweights.npy"


# can leave these if you want it's directories and filenames for generated output
PREPROCESS_TRAINING_DATA_OUTPUT_DIR = "preprocessed_training_data"
PREPROCESS_VALIDATION_DATA_OUTPUT_DIR = "preprocessed_validation_data"

VALIDATION_LABEL_WEIGHTS_PATH = "preprocessed_validation_data/labelweights.npy"
TRAINING_LABEL_WEIGHTS_PATH = "preprocessed_training_data/labelweights.npy"

TRAINING_OUTPUT_DIR = "training_results"
TRAINING_OUTPUT_DIR_PHYSICS = "training_results_physics"

TEST_TRAINING_OUTPUT_DIR = "test_training_results"
TEST_TRAINING_OUTPUT_DIR_PHYSICS = "test_training_results_physics"

EVAL_OUTPUT_DIR = "evaluation_results"
EVAL_OUTPUT_DIR_PHYSICS = "evaluation_results_physics"